language: java

jdk:
  - openjdk17

cache:
  directories:
    - $HOME/.m2

services:
  - docker

install:
  - mvn clean install -Dskiptest

script:
  - mvn test
  - cd partie
  - mvn failsafe:integration-test -Dit.test=partieController.TestPartieControllerIT#initPartieTest
  - cd ..

  - docker build anagrammeur -t scrabble:anagrammeur
  - docker build appariement -t scrabble:appariement
  - docker build partie -t scrabble:partie
  - docker build joueur -t scrabble:joueur

  - docker-compose up --scale joueur=4

